// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsXOslqVyrf0tJUCGFrF9o9_3FRjC0Q8',
    appId: '1:858915225723:web:a5675d31397287030062de',
    messagingSenderId: '858915225723',
    projectId: 'doi-coffee-project',
    authDomain: 'doi-coffee-project.firebaseapp.com',
    storageBucket: 'doi-coffee-project.appspot.com',
    measurementId: 'G-529DHRYVR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmKclNINVLMTAtVMJvddTfeECA1z4NISg',
    appId: '1:858915225723:android:0381ef28fb61a1680062de',
    messagingSenderId: '858915225723',
    projectId: 'doi-coffee-project',
    storageBucket: 'doi-coffee-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskk-GLql5leRsSmddrHpWWHozMLKw2-M',
    appId: '1:858915225723:ios:2169768e91cfde280062de',
    messagingSenderId: '858915225723',
    projectId: 'doi-coffee-project',
    storageBucket: 'doi-coffee-project.appspot.com',
    iosBundleId: 'com.example.doiCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAskk-GLql5leRsSmddrHpWWHozMLKw2-M',
    appId: '1:858915225723:ios:2169768e91cfde280062de',
    messagingSenderId: '858915225723',
    projectId: 'doi-coffee-project',
    storageBucket: 'doi-coffee-project.appspot.com',
    iosBundleId: 'com.example.doiCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADsXOslqVyrf0tJUCGFrF9o9_3FRjC0Q8',
    appId: '1:858915225723:web:e07f6999ea2800b10062de',
    messagingSenderId: '858915225723',
    projectId: 'doi-coffee-project',
    authDomain: 'doi-coffee-project.firebaseapp.com',
    storageBucket: 'doi-coffee-project.appspot.com',
    measurementId: 'G-TER5KPS6MS',
  );
}
